class UserModel {
  int? id;
  String? username;
  String? email;
  String? phone;
  String? image;
  int? role;
  String? adress;
  String? aboutUs;
  // List<Products>? products;
  // List<BuyedProducts>? buyedProducts;
  // List<Favourites>? favourites;
  // List<SaledProducts>? saledProducts;

  UserModel({
    this.id,
    this.username,
    this.email,
    this.phone,
    this.image,
    this.role,
    this.adress,
    this.aboutUs,
  });

  UserModel.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    username = json['username'];
    email = json['email'];
    phone = json['phone'];
    image = json['image'];
    role = json['role'];
    adress = json['adress'];
    aboutUs = json['about_us'];
  }
}



/**
 class Autogenerated {
  List<User>? user;

  Autogenerated({this.user});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['user'] != null) {
      user = <User>[];
      json['user'].forEach((v) {
        user!.add(new User.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.user != null) {
      data['user'] = this.user!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class User {
  int? id;
  String? username;
  String? email;
  String? phone;
  Null? emailVerifiedAt;
  Null? image;
  int? role;
  Null? adress;
  Null? aboutUs;
  String? createdAt;
  String? updatedAt;
  List<Products>? products;
  List<Null>? buyedProducts;
  List<Favourites>? favourites;
  List<Null>? saledProducts;

  User(
      {this.id,
      this.username,
      this.email,
      this.phone,
      this.emailVerifiedAt,
      this.image,
      this.role,
      this.adress,
      this.aboutUs,
      this.createdAt,
      this.updatedAt,
      this.products,
      this.buyedProducts,
      this.favourites,
      this.saledProducts});

  User.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    username = json['username'];
    email = json['email'];
    phone = json['phone'];
    emailVerifiedAt = json['email_verified_at'];
    image = json['image'];
    role = json['role'];
    adress = json['adress'];
    aboutUs = json['about_us'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
    if (json['products'] != null) {
      products = <Products>[];
      json['products'].forEach((v) {
        products!.add(new Products.fromJson(v));
      });
    }
    if (json['buyed_products'] != null) {
      buyedProducts = <Null>[];
      json['buyed_products'].forEach((v) {
        buyedProducts!.add(new Null.fromJson(v));
      });
    }
    if (json['favourites'] != null) {
      favourites = <Favourites>[];
      json['favourites'].forEach((v) {
        favourites!.add(new Favourites.fromJson(v));
      });
    }
    if (json['saled_products'] != null) {
      saledProducts = <Null>[];
      json['saled_products'].forEach((v) {
        saledProducts!.add(new Null.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['username'] = this.username;
    data['email'] = this.email;
    data['phone'] = this.phone;
    data['email_verified_at'] = this.emailVerifiedAt;
    data['image'] = this.image;
    data['role'] = this.role;
    data['adress'] = this.adress;
    data['about_us'] = this.aboutUs;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    if (this.products != null) {
      data['products'] = this.products!.map((v) => v.toJson()).toList();
    }
    if (this.buyedProducts != null) {
      data['buyed_products'] =
          this.buyedProducts!.map((v) => v.toJson()).toList();
    }
    if (this.favourites != null) {
      data['favourites'] = this.favourites!.map((v) => v.toJson()).toList();
    }
    if (this.saledProducts != null) {
      data['saled_products'] =
          this.saledProducts!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Products {
  int? id;
  int? userId;
  String? title;
  String? description;
  int? price;
  String? category;
  int? rate;
  int? discount;
  int? online;
  String? image;
  String? createdAt;
  String? updatedAt;
  List<Null>? productImages;
  List<Null>? comments;

  Products(
      {this.id,
      this.userId,
      this.title,
      this.description,
      this.price,
      this.category,
      this.rate,
      this.discount,
      this.online,
      this.image,
      this.createdAt,
      this.updatedAt,
      this.productImages,
      this.comments});

  Products.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    userId = json['user_id'];
    title = json['title'];
    description = json['description'];
    price = json['price'];
    category = json['category'];
    rate = json['rate'];
    discount = json['discount'];
    online = json['online'];
    image = json['image'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
    if (json['product_images'] != null) {
      productImages = <Null>[];
      json['product_images'].forEach((v) {
        productImages!.add(new Null.fromJson(v));
      });
    }
    if (json['comments'] != null) {
      comments = <Null>[];
      json['comments'].forEach((v) {
        comments!.add(new Null.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['user_id'] = this.userId;
    data['title'] = this.title;
    data['description'] = this.description;
    data['price'] = this.price;
    data['category'] = this.category;
    data['rate'] = this.rate;
    data['discount'] = this.discount;
    data['online'] = this.online;
    data['image'] = this.image;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    if (this.productImages != null) {
      data['product_images'] =
          this.productImages!.map((v) => v.toJson()).toList();
    }
    if (this.comments != null) {
      data['comments'] = this.comments!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Favourites {
  int? id;
  int? productId;
  int? userId;
  String? createdAt;
  String? updatedAt;

  Favourites(
      {this.id, this.productId, this.userId, this.createdAt, this.updatedAt});

  Favourites.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    productId = json['product_id'];
    userId = json['user_id'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['product_id'] = this.productId;
    data['user_id'] = this.userId;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    return data;
  }
}
 */